### ISSUE TITLE
Javascript line continuations in strings causes errors

### ISSUE THREAD

**Issue by shaicoleman** [sbecker/asset_packager#8]
```
vendor/plugins/asset_packager/lib/jsmin.rb:113:in `action': Unterminated string literal (RuntimeError)
    from vendor/plugins/asset_packager/lib/jsmin.rb:195:in `jsmin'
    from vendor/plugins/asset_packager/lib/jsmin.rb:205
```

Which is caused by code such as:
    styleSheet.addRule(
        '.typeface-js-selected-text', 
        '-ms-filter: \
            "Chroma(color=black) \
            progid:DXImageTransform.Microsoft.MaskFilter(Color=white) \
            progid:DXImageTransform.Microsoft.MaskFilter(Color=blue) \
            alpha(opacity=30)" !important; \
        color: black; \
        font-family: Modern; \
        position: absolute; \
        white-space: pre; \
        filter: alpha(opacity=0);'
    );

**Comment by cainlevy** [comment]
you may try http://github.com/cainlevy/asset_packager/commit/4430b2cbb7b43f4560dcf67938265dcffb056623
